Catkin-ProjectName: actionlib
Version: 1.7.1
Description: A standardized interface for interfacing with preemptible tasks.

Depends: common_msgs
Author: Eitan Marder-Eppstein, Vijay Pradeep
Maintainer:
Homepage: http://ros.org/wiki/actionlib

Catkin-DebRulesType: cmake
Catkin-CopyrightType:  willowgarage

Release-Pull: git://github.com/wg-debs/actionlib.git
Release-Push: git@github.com:wg-debs/actionlib.git
